### ISSUE TITLE
Codes for alignments and counts

### ISSUE THREAD

**Issue by lrjoshi** [ajwilk/2020_Wilk_COVID#1]
Hi ajwilk, 

Would you mind adding a file containing the codes that you used for alignment and counting?  

Thanks

**Comment by ajwilk** [comment]
Sorry for the delay. I've uploaded code used for alignment and count matrix generation to ```code/sample_alignment.sh```, and I've documented the versions of the packages used there. ```code/config.xml``` specifies the read structure for Seq-Well and is required by dropEst. Let me know if there's anything else you're looking for.

**Comment by lrjoshi** [comment]
Thanks. The paper is really interesting. The figures are great. I wanted to replicate some of the figures. Thanks again for putting all these codes online. I will let you know if I notice something interesting.
