### ISSUE TITLE
mergeCM - Unsupported type for sort

### ISSUE THREAD

**Issue by InfoSuresh** [ajwilk/2020_Wilk_COVID#10]
Hi @ajwilk 
I created count matrices from raw reads and I used 13 matrices files for analysis. I am getting error in the mergeCM function.
Code:-
covid_combined.emat <- mergeCM(cm.pp, type = "emat")
Error:-
Error in grr::matches(by.x, by.y, all.x, all.y, nomatch = NA) 
   Unsupported type for sort.

How to resolve this. Thanks in advance.

**Comment by ajwilk** [comment]
This is a problem with ```mergeCM``` not appropriately handling 13 matrices. That repo is not actively maintained; this most straightforward solution is to use all 14 count matrices, including the one that's not on GEO (https://github.com/ajwilk/2020_Wilk_COVID/tree/master/data/count_matrices). Let me know if more assistance is needed.
