### ISSUE TITLE
Error In Adding Metadata

### ISSUE THREAD

**Issue by robin1-2** [ajwilk/2020_Wilk_COVID#11]
rownames(metadata_combined) <- rownames(covid_combined@meta.data)
This line gives the following error: 

_Warning: Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length_

Because the metadata file you provide ("https://raw.githubusercontent.com/ajwilk/2020_Wilk_COVID/master/code/COVID-19_metadata_repo.csv") have different "orig.ident" names than created Seurat Object. 

Problem is solved simply by changing the "orig.ident" names in the metadata file (eg. from "covid_556" to "556").

**Comment by ajwilk** [comment]
thanks for the catch, I've added a comment to the markdown for this
