### ISSUE TITLE
Problem in filtering markers. 

### ISSUE THREAD

**Issue by robin1-2** [ajwilk/2020_Wilk_COVID#12]
covid_combined.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
gives the following error: 

Error: Problem with `filter()` input `..1`.
i Input `..1` is `top_n_rank(10, avg_logFC)`.
x object 'avg_logFC' not found
i The error occurred in group 1: cluster = 0.

Does the argument of top_n "wt =avg_logFC" or "wt = avg_log2FC"?

**Comment by ajwilk** [comment]
This is a change in the output of ```FindMarkers``` for Seurat v4, see the documentation here: https://satijalab.org/seurat/articles/v4_changes.html
