### ISSUE TITLE
How did the object "EpicPreHS" come about? Not explained in the script, hope to know

### ISSUE THREAD

**Issue by Jiahe-Sun** [ajwilk/2020_Wilk_COVID#14]
![image](https://user-images.githubusercontent.com/69581197/154619579-2e67174f-882b-4650-9b49-1ddf0f315b6d.png)

pre-processing

```{r pre-process}
cm.pp <- mapply(EpicPreHS, cm.files, orig.ident = names(cm.files), SIMPLIFY = F)
```

**Comment by ajwilk** [comment]
Hi there, ```EpicPreHS``` is a function from the library ```EpicTools``` available at: https://github.com/ajwilk/EpicTools

**Comment by Jiahe-Sun** [comment]
ok！ thank you！
