### ISSUE TITLE
warning when running EpicPreHS in file "generating_Searat_object.Rmd"

### ISSUE THREAD

**Issue by Kittenlovefish** [ajwilk/2020_Wilk_COVID#4]
Hi, 
when I run the script, a warning pops up when I run this line: 
##pre-processing
cm.pp <- mapply(EpicPreHS, cm.files, orig.ident = names(cm.files), SIMPLIFY = F)

warning:
In (function (cm_name, min.counts = 500, max.counts = 15000,  ... :
  The resulting cell names will be strange if the input object name does not end with '.cm'

Would you mind clarifying if this warning will affect the results?

**Comment by ajwilk** [comment]
No, this warning will not affect the results, and only concerns the way in which cells are named (and subsequently how these names are detected as sample identities by Seurat). I've written these functions into a package (https://github.com/ajwilk/EpicTools) that has this warning removed when `orig.ident` is specified. I've updated this repository to require that package as a library and removed the outdated functions from `additionalFunctions_repo.R`.
