### ISSUE TITLE
Can you please provide bam files?

### ISSUE THREAD

**Issue by urmi-21** [ajwilk/2020_Wilk_COVID#5]
Hello,
I really appreciate you creating this repository and sharing your code data analysis you performed in your wonderful paper. I was wondering if it will be possible for you to share the aligned reads as bam files? I am trying to re-analyse the data from a different perspective and having the bam files to start with will be really helpful.
So, is it possible for you to share the bam files generated by https://github.com/ajwilk/2020_Wilk_COVID/blob/master/code/sample_alignment.sh script?
I will really appreciate your help.
Thank you.

**Comment by ajwilk** [comment]
Hi @urmi-21,
I am now hosting the bams for this study at this address: https://drive.google.com/drive/folders/1qf62ip8WorEV-KLf_WSi8AMyyMoNdfln?usp=sharing

It will likely take some time for them to transfer and appear. Please note that we cannot share the bam for patient 560 (AKA C6) as they explicitly did not consent to the sharing of sequence-level information that is included in the bam. 

Best,
Aaron

**Comment by urmi-21** [comment]
This is really helpful.
Thanks again. :)
