### ISSUE TITLE
adata object related to the plasma cell to neutrophil transition for dynamo analysis

### ISSUE THREAD

**Issue by Xiaojieqiu** [ajwilk/2020_Wilk_COVID#6]
Hi Aaron @ajwilk, I am really interested in the possible plasma to neutrophil transition as proposed in your paper. While it seems controversial (as I followed the papers of discussion between you and Jose and Joseph), I wonder whether the computational framework, dynamo (https://github.com/aristoteleo/dynamo-release), I developed can provide some further validation for your conclusion. I am personally a believer in this kind of cell-fate transition in general. 

Would you mind to share the adata object (saved as h5ad format) that can be used to perform this analysis. The adata object that includes intron/exon raw UMI for all cells and your cell type annotation, as well as the original UMAP embedding for the full dataset will be ideal.  The UMAP embedding for the subset of plasm and neutrophil cells that are used for the transition analysis will be helpful too.

**Comment by Xiaojieqiu** [comment]
Hi @ajwilk I am able to pull the data by following your code. dynamo is also able to retrieve the same plasma to neutrophil lineage transition. I am going to do some follow-up vector field enabled analysis (like acceleration, curvature, divergence, etc). If you are interested, I am happy to share those results and get some opinions on them. 

<img width="449" alt="dynamo analysis at 1 18 46 PM" src="https://user-images.githubusercontent.com/7456281/100523207-aa6e6780-317c-11eb-8498-24ce3e7a247f.png">

**Comment by ajwilk** [comment]
Hi @Xiaojieqiu so sorry for the delayed reply (have been on holiday this week), but glad you were able to pull the data and very interesting the putative transition looks similar with dynamo. 

Let me know if there’s anything else you could use from me (I’m personally curious to see how this looks on the embeddings I’ve been using) and I’d love to hear what you come across with additional analyses. We’re also trying to validate/refute this with orthogonal techniques too... so please keep in touch!
