### ISSUE TITLE
How to create a AnnData by mtx and csv file

### ISSUE THREAD

**Issue by lucc9993** [ajwilk/2020_Wilk_COVID#9]
I'm very interested in the part of RNA velocity analysis in your article. Can you provide the code for creating AnnData by .mtx and .csv? Thank you very much!

**Comment by ajwilk** [comment]
Hi there, thanks for your interest in our work! Seurat Disk (https://github.com/mojaveazure/seurat-disk) may now have some more convenient ways to convert a Seurat object with multiple "assays"/"layers" into AnnData but this is one way to build it piece by piece: 

```
import scvelo as scv
scv.logging.print_version()
import anndata as ad
import pandas as pd

sdata = ad.read_mtx("~/object.emat.mtx") #spliced layer
sdata.layers['spliced'] = sdata.X
ndata = ad.read_mtx("~/object.nmat.mtx") #unspliced layer
sdata.layers['unspliced'] = ndata.X
pd_obs = pd.read_csv("~/object.obs.csv") #annotation of observations
pd_obsm = pd.read_csv("~/object.obsm.csv") #embedding
sdata.obs = pd_obs
sdata.obsm["X_umap"] = pd_obsm.values
pd_obs_names = pd.read_table("~/object.obs_names.txt", header=None)[0].tolist() #names of observations
sdata.obs_names = pd_obs_names
pd_var_names = pd.read_table("~/object.var_names.txt", header=None)[0].tolist() #names of variables
sdata.var_names = pd_var_names
sdata
```

Biologically speaking, I'll also point you to our recent preprint (https://www.biorxiv.org/content/10.1101/2020.12.18.423363v1.full) that performs the same analysis on many more donors and across a wider range of disease severity (data are now available here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE174072). While the phenotypic relationship between plasmablasts and immature neutrophils is still present, a transdifferentiation bridge is much less clear. We are still working on orthogonal experiments that will be necessary to validate or refute the hypothesis.
